

/*
 * AUTO-GENERATION WARNING:
 *     This file has been automatically generated from "version.h.in.cmake".
 *     DO NOT edit this file, as any changes will be automatically discarded.
 */
 
 namespace ATML
 {
 
	int ATMLVersionMajor()
	{
		return 0;
	};

	int ATMLVersionMinor()
	{
		return 1;
	}; 

	int ATMLVersionPatch()
	{
		return 0;
	}; 

	const char* ATMLCodeName
	{
		return "Platon";
	};

	const char* ATMLName
	{
		return "ATML";
	};

	const char* ATMLCopyrightYears
	{
		return "2015";
	};

	const char* ATMLVersionType
	{
		return "SNAPSHOT";
	};

	const char* ATMLVersionString
	{
		return "0.1.0-SNAPSHOT";
	};

	const char* ATMLVendorID
	{
		return "com.yourcompany";
	};

	const char* ATMLVendorName
	{
		return "Your Company";
	};

	const char* ATMLVendorURL
	{
		return "yourcompany.com";
	};

	const char* ATMLVendorID
	{
		return "com.yourcompany";
	};

}
