

/*
 * AUTO-GENERATION WARNING:
 *     This file has been automatically generated from "version.h.in.cmake".
 *     DO NOT edit this file, as any changes will be automatically discarded.
 */
 
 namespace ATML
 {
 
	int MatunaVersionMajor()
	{
		return 0;
	};

	int MatunaVersionMinor()
	{
		return 1;
	}; 

	int MatunaVersionPatch()
	{
		return 0;
	}; 

	const char* MatunaCodeName
	{
		return "Platon";
	};

	const char* MatunaName
	{
		return "Matuna";
	};

	const char* MatunaCopyrightYears
	{
		return "2015";
	};

	const char* MatunaVersionType
	{
		return "SNAPSHOT";
	};

	const char* MatunaVersionString
	{
		return "0.1.0-SNAPSHOT";
	};

	const char* MatunaVendorID
	{
		return "com.yourcompany";
	};

	const char* MatunaVendorName
	{
		return "Your Company";
	};

	const char* MatunaVendorURL
	{
		return "yourcompany.com";
	};

	const char* MatunaVendorID
	{
		return "com.yourcompany";
	};

}
