

/*
 * AUTO-GENERATION WARNING:
 *     This file has been automatically generated from "version.h.in.cmake".
 *     DO NOT edit this file, as any changes will be automatically discarded.
 */
 
 namespace ATML
 {
 
	int @APPLICATION_NAME@VersionMajor()
	{
		return @APPLICATION_VERSION_MAJOR@;
	};

	int @APPLICATION_NAME@VersionMinor()
	{
		return @APPLICATION_VERSION_MINOR@;
	}; 

	int @APPLICATION_NAME@VersionPatch()
	{
		return @APPLICATION_VERSION_PATCH@;
	}; 

	const char* @APPLICATION_NAME@CodeName
	{
		return "@APPLICATION_CODENAME@";
	};

	const char* @APPLICATION_NAME@Name
	{
		return "@APPLICATION_NAME@";
	};

	const char* @APPLICATION_NAME@CopyrightYears
	{
		return "@APPLICATION_COPYRIGHT_YEARS@";
	};

	const char* @APPLICATION_NAME@VersionType
	{
		return "@APPLICATION_VERSION_TYPE@";
	};

	const char* @APPLICATION_NAME@VersionString
	{
		return "@APPLICATION_VERSION_STRING@";
	};

	const char* @APPLICATION_NAME@VendorID
	{
		return "@APPLICATION_VENDOR_ID@";
	};

	const char* @APPLICATION_NAME@VendorName
	{
		return "@APPLICATION_VENDOR_NAME@";
	};

	const char* @APPLICATION_NAME@VendorURL
	{
		return "@APPLICATION_VENDOR_URL@";
	};

	const char* @APPLICATION_NAME@VendorID
	{
		return "@APPLICATION_VENDOR_ID@";
	};

}